language: ruby
cache: bundler
before_install:
  - yes | gem update --system --force
  - gem install bundler
  - wget -P _data/ https://raw.githubusercontent.com/jensdufour/ScoutsNinove/master/_data/programma.yml
  - wget -P _data/ https://raw.githubusercontent.com/jensdufour/ScoutsNinove/master/_data/voorwoord.yml
install:
  - bundle install
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ./site
    on:
      branch: master
