language: ruby
cache: bundler
before_install: 
  - gem update bundler
install:
  - bundle install
branches:
  only:
  - master
script:
  - JEKYLL_ENV=bundle exec jekyll build --destination site
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: ./site
    on:
      branch: master
