language: ruby
cache: bundler
before_install: 
  - gem update bundler
install:
  - bundle install
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true # opt in to dpl v2
