language: ruby
cache: bundler
before_install: 
  - gem update bundler
install:
  - bundle install
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master